version: '3'

services:
  airflow-init:
    image: apache/airflow:latest
    networks:
      - airflow
    depends_on:
      - airflow-db
    environment: 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    command: >
      bash -c "airflow db init && airflow users create 
      --username admin 
      --password admin 
      --firstname Charles 
      --lastname Talaga 
      --role Admin 
      --email charlesftalaga@gmail.com"

  airflow-webserver:
    image: apache/airflow:latest
    networks:
      - airflow
    depends_on:
      - airflow-init
    environment: 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:latest
    networks:
      - airflow
    depends_on:
      - airflow-webserver
    restart: on-failure:3
    environment: 
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

  airflow-db:
    image: postgres:latest
    networks:
      - airflow
    environment:
      POSTGRES_USER: airflow   
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

networks:
  airflow:
    driver: bridge 